name: compileAPKIPA

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  compile_IPA_APK:
    runs-on: macos-latest


    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Read app version from YAML
      run: |
        APP_VERSION=$(sed -n 's/^version:[ ]*//p' pubspec.yaml | tr -d '[:space:]')
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'
        channel: 'stable'
    - uses: oberhauser-dev/flutter-release-action@v0
      with:
        token: ${{ github.token }}
        dry-run: true
        app-name: 'moonchain_app'
        app-version: ${{ env.APP_VERSION }}
        tag: ${{ github.ref }}
        build-type: 'ipa'
        build-args: |-
            --flavor product
            --release
