name: Build and distribute

on:
  push:
    branches:
      - pre_main_qa

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Generate build number
        uses:  snakka-hv/action-custom-build-number@master 
        with:
          token: ${{secrets.DART_TOKEN}}        
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Set Version Code
        run: |
          echo "Received PR count: $BUILD_NUMBER"
          echo "VERSION_CODE=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "Set VERSION_CODE to: $BUILD_NUMBER"
        shell: bash

      - uses: sheenhx/action-flutter-build-android@v3
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          build-cmd: flutter build apk --flavor product --release --build-number=${{ env.VERSION_CODE }}
          working-directory: ./
          
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/flutter-apk/app-product-release.apk

      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-product-release.apk
          token: ${{ secrets.DART_TOKEN }}
          tag: ${{ github.ref_name }}

