name: Build and distribute

on:
  push:
    branches:
      - pre_main_qa

jobs:
  build-apk:
    name: build-apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Generate
        id: generate
        uses: AcmeSoftwareLLC/app-build-number@v1
        with:
          timezone: Asia/Kathmandu
    
      - name: Display the generated build number
        run: echo "Build Number > ${{ steps.generate.outputs.build-number }}"


      - name: Set Version Code
        run: |
          echo "Received Number: ${{ github.run_number }}"
          echo "VERSION_CODE=${{ github.run_number }}" >> $GITHUB_ENV
          echo "Set VERSION_CODE to: ${{ github.run_number }}"
        shell: bash

      - uses: sheenhx/action-flutter-build-android@v3
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          build-cmd: flutter build apk --flavor product --release --build-number=${{ env.VERSION_CODE }}
          working-directory: ./
          
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/flutter-apk/app-product-release.apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-product-release.apk
          token: ${{ secrets.DART_TOKEN }}
          tag: ${{ steps.generate.outputs.build-number }}

  build-macos:
    name: Build-ios
    runs-on: macos-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: sheenhx/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --build-number=$(( 15 + ${{ github.run_number }}))
          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          # Try running the build locally with the build command to be sure of this path
          path: build/ios/ipa/App.ipa
