name: Submit to Google and Apple

on:
  push:
    branches:
      - google

jobs:
  build-apk:
    name: Build-aab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'


      - name: Set Version Code
        run: |
          echo "Received Number: ${{ github.run_number }}"
          echo "VERSION_CODE=${{ github.run_number }}" >> $GITHUB_ENV
          echo "Set VERSION_CODE to: ${{ github.run_number }}"
        shell: bash

      - uses: sheenhx/action-flutter-build-android@v3
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          build-cmd: flutter build appbundle --release --build-number=${{ env.VERSION_CODE }} --flavor googlePlay
          working-directory: ./

      - name: Rename APK
        run: mv build/app/outputs/bundle/googlePlayRelease/app-googlePlay-release.aab build/app/outputs/bundle/googlePlayRelease/moonchain.aab
          
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/bundle/googlePlayRelease/moonchain.aab

      - name: Archive symbols
        uses: actions/upload-artifact@v4
        with:
          name: release-symbol
          path: build/app/intermediates

          
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.moonchain.mxc
          releaseFiles: build/app/outputs/bundle/googlePlayRelease/moonchain.aab
          track: alpha
          status: draft
          debugSymbols: build/app/intermediates
